/* --------------------------------------------------------------------------------
 #
 #	4DPlugin-XLSXIO.h
 #	source generated by 4D Plugin Wizard
 #	Project : XLSXIO
 #	author : miyako
 #	2020/09/02
 #  
 # --------------------------------------------------------------------------------*/

#ifndef PLUGIN_XLSXIO_H
#define PLUGIN_XLSXIO_H

#include "4DPluginAPI.h"
#include "xlsxio_read.h"
#include "xlsxio_write.h"

#include <stdio.h>
#include <stdlib.h>

#include "C_TEXT.h"
#include "C_LONGINT.h"

#include "json/json.h"

#pragma mark -

void XLSX_TO_JSON(PA_PluginParameters params);
void JSON_TO_XLSX(PA_PluginParameters params);
void XLSX_SHEET_NAMES(PA_PluginParameters params);

#endif /* PLUGIN_XLSXIO_H */
