/* --------------------------------------------------------------------------------
 #
 #	4DPlugin.h
 #	source generated by 4D Plugin Wizard
 #	Project : XLSXIO
 #	author : miyako
 #	2017/08/16
 #
 # --------------------------------------------------------------------------------*/

#include "xlsxio_read.h"
#include "xlsxio_write.h"
#include "libjson.h"

#include <stdio.h>
#include <stdlib.h>

// --- Read
void XLSX_TO_JSON(sLONG_PTR *pResult, PackagePtr pParams);

// --- Write
void JSON_TO_XLSX(sLONG_PTR *pResult, PackagePtr pParams);
